// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x70, 0x63,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x78, 0x0a, 0x17, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x5d, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x70, 0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x64, 0x1a,
	0x20, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x70,
	0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x42, 0x03, 0x5a, 0x01, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_service_proto_goTypes = []interface{}{
	(*StudentQueryId)(nil), // 0: studentQueryRpc.content.StudentQueryId
	(*Student)(nil),        // 1: studentQueryRpc.content.Student
}
var file_service_proto_depIdxs = []int32{
	0, // 0: studentQueryRpc.service.StudentInfoQueryService.QueryStudentInfo:input_type -> studentQueryRpc.content.StudentQueryId
	1, // 1: studentQueryRpc.service.StudentInfoQueryService.QueryStudentInfo:output_type -> studentQueryRpc.content.Student
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_content_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StudentInfoQueryServiceClient is the client API for StudentInfoQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentInfoQueryServiceClient interface {
	QueryStudentInfo(ctx context.Context, in *StudentQueryId, opts ...grpc.CallOption) (*Student, error)
}

type studentInfoQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentInfoQueryServiceClient(cc grpc.ClientConnInterface) StudentInfoQueryServiceClient {
	return &studentInfoQueryServiceClient{cc}
}

func (c *studentInfoQueryServiceClient) QueryStudentInfo(ctx context.Context, in *StudentQueryId, opts ...grpc.CallOption) (*Student, error) {
	out := new(Student)
	err := c.cc.Invoke(ctx, "/studentQueryRpc.service.StudentInfoQueryService/QueryStudentInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentInfoQueryServiceServer is the server API for StudentInfoQueryService service.
type StudentInfoQueryServiceServer interface {
	QueryStudentInfo(context.Context, *StudentQueryId) (*Student, error)
}

// UnimplementedStudentInfoQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStudentInfoQueryServiceServer struct {
}

func (*UnimplementedStudentInfoQueryServiceServer) QueryStudentInfo(context.Context, *StudentQueryId) (*Student, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryStudentInfo not implemented")
}

func RegisterStudentInfoQueryServiceServer(s *grpc.Server, srv StudentInfoQueryServiceServer) {
	s.RegisterService(&_StudentInfoQueryService_serviceDesc, srv)
}

func _StudentInfoQueryService_QueryStudentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentQueryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentInfoQueryServiceServer).QueryStudentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/studentQueryRpc.service.StudentInfoQueryService/QueryStudentInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentInfoQueryServiceServer).QueryStudentInfo(ctx, req.(*StudentQueryId))
	}
	return interceptor(ctx, in, info, handler)
}

var _StudentInfoQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "studentQueryRpc.service.StudentInfoQueryService",
	HandlerType: (*StudentInfoQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryStudentInfo",
			Handler:    _StudentInfoQueryService_QueryStudentInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
