package constant

var KAFKA_ADDRESS = "172.18.0.3:9092"

var TOPIC = "GO_KAFKA_TOPIC"
var KEY = "GO_KAFKA_MESSAGE_KEY"
var PARTITION_0 int32 = 0
var PARTITION_1 int32 = 1
var CONSUMER_GROUP = "CONSUMER_GROUP_FOR_GO_KAFKA_TOPIC"
