// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"gorm_gen_demo/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.Hobby{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Hobby{}) fail: %s", err)
	}
}

func Test_hobbyQuery(t *testing.T) {
	hobby := newHobby(_gen_test_db)
	hobby = *hobby.As(hobby.TableName())
	_do := hobby.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(hobby.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <hobby> fail:", err)
		return
	}

	_, ok := hobby.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from hobby success")
	}

	err = _do.Create(&model.Hobby{})
	if err != nil {
		t.Error("create item in table <hobby> fail:", err)
	}

	err = _do.Save(&model.Hobby{})
	if err != nil {
		t.Error("create item in table <hobby> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Hobby{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <hobby> fail:", err)
	}

	_, err = _do.Select(hobby.ALL).Take()
	if err != nil {
		t.Error("Take() on table <hobby> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <hobby> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <hobby> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <hobby> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Hobby{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <hobby> fail:", err)
	}

	_, err = _do.Select(hobby.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <hobby> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <hobby> fail:", err)
	}

	_, err = _do.Select(hobby.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <hobby> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <hobby> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <hobby> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <hobby> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Hobby{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <hobby> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <hobby> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <hobby> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <hobby> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <hobby> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <hobby> fail:", err)
	}
}

var HobbyFilterWithIdTestCase = []TestCase{}

func Test_hobby_FilterWithId(t *testing.T) {
	hobby := newHobby(_gen_test_db)
	do := hobby.WithContext(context.Background()).Debug()

	for i, tt := range HobbyFilterWithIdTestCase {
		t.Run("FilterWithId_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FilterWithId(tt.Input.Args[0].(int))
			assert(t, "FilterWithId", res1, tt.Expectation.Ret[0])
			assert(t, "FilterWithId", res2, tt.Expectation.Ret[1])
		})
	}
}
